//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CPInBillDetail
    {
        public int FID { get; set; }
        public int FPID { get; set; }
        public Nullable<int> FCPXiMaID { get; set; }
        public int FItemID { get; set; }
        public string FBatchNo { get; set; }
        public Nullable<decimal> FWeight { get; set; }
        public string FUnitName { get; set; }
        public Nullable<int> FNum { get; set; }
        public string FMemo { get; set; }
        public string FWareCode { get; set; }
        public string FLocationCode { get; set; }
        public Nullable<System.DateTime> FInDate { get; set; }
        public Nullable<decimal> FKFPeriod { get; set; }
        public string FSourceBillNo { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public Nullable<decimal> UDF06 { get; set; }
        public Nullable<decimal> UDF07 { get; set; }
        public Nullable<decimal> UDF08 { get; set; }
        public Nullable<decimal> UDF09 { get; set; }
        public Nullable<decimal> UDF10 { get; set; }
    }
}
