//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMTDBContainer : DbContext
    {
        public EMTDBContainer()
            : base("name=EMTDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_DY_YZK> t_DY_YZK { get; set; }
        public virtual DbSet<t_DY_YZKEntry1> t_DY_YZKEntry1 { get; set; }
        public virtual DbSet<t_DY_GYLC> t_DY_GYLC { get; set; }
        public virtual DbSet<t_DY_GYLCEntry> t_DY_GYLCEntry { get; set; }
        public virtual DbSet<t_DY_YZKEntry2> t_DY_YZKEntry2 { get; set; }
    }
}
