//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JXCDBContainer : DbContext
    {
        public JXCDBContainer()
            : base("name=JXCDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_CPInBillDetail> t_CPInBillDetail { get; set; }
        public virtual DbSet<t_CPInBillHeader> t_CPInBillHeader { get; set; }
        public virtual DbSet<t_FGHCPIn> t_FGHCPIn { get; set; }
        public virtual DbSet<t_DYJXC_GXHB> t_DYJXC_GXHB { get; set; }
    }
}
