//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_YZKEntry2
    {
        public int FEntryID { get; set; }
        public int FID { get; set; }
        public int FIndex { get; set; }
        public int FJB { get; set; }
        public int FQty { get; set; }
        public int FRG { get; set; }
        public int FLZQty { get; set; }
        public string FYCJL { get; set; }
        public int FYCQty { get; set; }
        public int FDepartment { get; set; }
        public int FSJDepartment { get; set; }
        public int FCurWorkProcedure { get; set; }
        public int FSCJT { get; set; }
        public Nullable<System.DateTime> FJSTime { get; set; }
        public Nullable<System.DateTime> FKSTime { get; set; }
        public Nullable<System.DateTime> FEndTime { get; set; }
        public int FXDGX { get; set; }
        public string FOprationer { get; set; }
        public bool FBolCurWP { get; set; }
        public bool FCheckBox { get; set; }
        public Nullable<System.DateTime> FFinishTime { get; set; }
    }
}
