//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DYJXC_GXHB
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FRecDate { get; set; }
        public string FGH { get; set; }
        public int FItemID { get; set; }
        public int FProcedureID { get; set; }
        public string FOperType { get; set; }
        public Nullable<decimal> FNum { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
        public string FOperMan { get; set; }
        public string FMemo { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
        public string UDF06 { get; set; }
        public string UDF07 { get; set; }
        public string UDF08 { get; set; }
        public string UDF09 { get; set; }
        public string UDF10 { get; set; }
        public Nullable<decimal> UDF11 { get; set; }
        public Nullable<decimal> UDF12 { get; set; }
        public Nullable<decimal> UDF13 { get; set; }
        public Nullable<decimal> UDF14 { get; set; }
        public Nullable<decimal> UDF15 { get; set; }
        public Nullable<decimal> UDF16 { get; set; }
        public Nullable<decimal> UDF17 { get; set; }
        public Nullable<decimal> UDF18 { get; set; }
        public Nullable<decimal> UDF19 { get; set; }
        public Nullable<decimal> UDF120 { get; set; }
        public Nullable<int> FJT { get; set; }
        public Nullable<int> FIndex { get; set; }
    }
}
