//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_YZK
    {
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public int FBiller { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public int FChecker { get; set; }
        public Nullable<System.DateTime> FChekcDate { get; set; }
        public string FOrderNo { get; set; }
        public int FAmountType { get; set; }
        public int FBase { get; set; }
        public int FOrganization { get; set; }
        public string FCustomerNo { get; set; }
        public Nullable<System.DateTime> FDeliveryDate { get; set; }
        public int FBase1 { get; set; }
        public int FQty { get; set; }
        public decimal FWeight { get; set; }
        public string FPBNote { get; set; }
        public string FAddress { get; set; }
        public string FWorkFlow { get; set; }
        public string FSL { get; set; }
        public string FDD { get; set; }
        public string FSG { get; set; }
        public string FDXFK { get; set; }
        public string FJB { get; set; }
        public string FQB { get; set; }
        public string FJSZ { get; set; }
        public string FJRY { get; set; }
        public string FAcross { get; set; }
        public string FStraight { get; set; }
        public string FTweak { get; set; }
        public string FZT { get; set; }
        public string FJD { get; set; }
        public string FNOTE { get; set; }
        public int FItemid { get; set; }
        public int FRow { get; set; }
        public string FGH { get; set; }
        public string FDDBZ { get; set; }
        public string fkz { get; set; }
        public string fjz { get; set; }
        public decimal FPZ1 { get; set; }
        public decimal FPZ2 { get; set; }
        public decimal FPZ3 { get; set; }
        public decimal FPZ4 { get; set; }
        public decimal FPZ5 { get; set; }
        public decimal FPZ6 { get; set; }
        public decimal FPZ7 { get; set; }
        public decimal FPZ8 { get; set; }
        public decimal FPZ9 { get; set; }
        public decimal FPZ10 { get; set; }
        public decimal FPZ11 { get; set; }
        public decimal FPZ12 { get; set; }
        public decimal FPZ13 { get; set; }
        public decimal FPZ14 { get; set; }
        public decimal FPZ15 { get; set; }
        public decimal FPZ16 { get; set; }
        public decimal FPZ17 { get; set; }
        public decimal FPZ18 { get; set; }
        public decimal FPZ19 { get; set; }
        public decimal FPZ20 { get; set; }
        public decimal FPZ21 { get; set; }
        public decimal FPZ22 { get; set; }
        public decimal FPZ23 { get; set; }
        public decimal FPZ24 { get; set; }
        public decimal FPZ25 { get; set; }
        public decimal FPZ26 { get; set; }
        public decimal FPZ27 { get; set; }
        public decimal FPZ28 { get; set; }
        public decimal FPZ29 { get; set; }
        public decimal FPZ30 { get; set; }
        public decimal FPZ31 { get; set; }
        public decimal FPZ32 { get; set; }
        public decimal FPZ33 { get; set; }
        public decimal FPZ34 { get; set; }
        public decimal FPZ35 { get; set; }
        public decimal FPZ36 { get; set; }
        public decimal FPZ37 { get; set; }
        public decimal FPZ38 { get; set; }
        public decimal FPZ39 { get; set; }
        public decimal FPZ40 { get; set; }
        public decimal FPZ41 { get; set; }
        public decimal FPZ42 { get; set; }
        public decimal FPZ43 { get; set; }
        public decimal FPZ44 { get; set; }
        public decimal FPZ45 { get; set; }
        public decimal FPZ46 { get; set; }
        public decimal FPZ47 { get; set; }
        public decimal FPZ48 { get; set; }
        public decimal FPZ49 { get; set; }
        public decimal FPZ50 { get; set; }
        public decimal FPZ51 { get; set; }
        public decimal FPZ52 { get; set; }
        public decimal FPZ53 { get; set; }
        public decimal FPZ54 { get; set; }
        public decimal FPZ55 { get; set; }
        public decimal FPZ56 { get; set; }
        public decimal FPZ57 { get; set; }
        public decimal FPZ58 { get; set; }
        public decimal FPZ59 { get; set; }
        public decimal FPZ60 { get; set; }
        public decimal FPZ61 { get; set; }
        public decimal FPZ62 { get; set; }
        public decimal FPZ63 { get; set; }
        public decimal FPZ64 { get; set; }
        public decimal FPZ65 { get; set; }
        public decimal FPZ66 { get; set; }
        public decimal FPZ67 { get; set; }
        public decimal FPZ68 { get; set; }
        public decimal FPZ69 { get; set; }
        public decimal FPZ70 { get; set; }
        public decimal FPZ71 { get; set; }
        public decimal FPZ72 { get; set; }
        public decimal FPZ73 { get; set; }
        public decimal FPZ74 { get; set; }
        public decimal FPZ75 { get; set; }
        public decimal FPZ76 { get; set; }
        public decimal FPZ77 { get; set; }
        public decimal FPZ78 { get; set; }
        public decimal FPZ79 { get; set; }
        public decimal FPZ80 { get; set; }
        public decimal FPZ81 { get; set; }
        public decimal FPZ82 { get; set; }
        public decimal FPZ83 { get; set; }
        public decimal FPZ84 { get; set; }
        public decimal FPZ85 { get; set; }
        public decimal FPZ86 { get; set; }
        public decimal FPZ87 { get; set; }
        public decimal FPZ88 { get; set; }
        public decimal FPZ89 { get; set; }
        public decimal FPZ90 { get; set; }
        public decimal FPZ91 { get; set; }
        public decimal FPZ92 { get; set; }
        public bool FClosed { get; set; }
        public string FGYLC { get; set; }
        public string FOrderCheckIdea1 { get; set; }
        public string FOrderCheckIdea2 { get; set; }
        public string FOrderCheckIdea3 { get; set; }
        public string FNoteForCP { get; set; }
        public decimal FSumPZ { get; set; }
        public string FSD { get; set; }
        public string FXJKZ { get; set; }
        public string FFundNo { get; set; }
        public int FBrandInfo { get; set; }
        public decimal FDecimal { get; set; }
        public decimal FDecimal1 { get; set; }
        public string FPBName { get; set; }
        public Nullable<System.DateTime> FDate1 { get; set; }
        public Nullable<System.DateTime> FDate2 { get; set; }
        public Nullable<System.DateTime> FDate4 { get; set; }
        public Nullable<System.DateTime> FDate5 { get; set; }
        public Nullable<System.DateTime> FDate6 { get; set; }
        public Nullable<System.DateTime> FDate3 { get; set; }
        public int FJJSX { get; set; }
        public string FZHPZ { get; set; }
        public Nullable<System.DateTime> FDate7 { get; set; }
        public int FNBSX { get; set; }
        public int FBZ { get; set; }
        public string FTMH { get; set; }
    }
}
